version: '3.7'
volumes:
  mongo-data3:
services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data3:/data/db
      - ./chi100easymongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: chi100easy


  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  bot:
    build: ./chi100easybot
    restart: always
    container_name: bot
    depends_on:
      - express

  express:
    build: ./chi100easyexpress
    restart: always
    container_name: express
    ports:
      - 4242:4242
    depends_on:
      - mongo

#  api:
#    build: ./chi100easyapi
#    restart: always
#    ports:
#      - 9001:9000
#    expose:
#      - "9000"
#    depends_on:
#      - mongo

  gui:
    build: ./chi100easygui
    restart: always
    container_name: gui
    ports:
      - 8080:8080
    volumes:
      - ./chi100easygui/docker/update.sh:/docker-entrypoint.d/update.sh
    environment:
      - "NODE_ENV=production"
    depends_on:
      - express

  nginx:
    build: ./chi100easybot-nginx
    restart: always
    container_name: botnginx
    ports:
      - "18080:80"
