version: '3.7'
volumes:
  mongo-data3:
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data3:/data/db
      - ./chi100easymongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: chi100easy


  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  bot:
    build: ./chi100easybot
    restart: always
    container_name: bot
    depends_on:
      - api

  api:
    build: ./chi100easyapi
    restart: always
    container_name: api
    ports:
      - 9001:9000
    expose:
      - "9000"
    depends_on:
      - mongo

