module.exports = {
    publicPath: '/chi100easy',
    pages: {
        index: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'index.html',
            title: 'Начальная',
            chunks: ['chunk-vendors', 'chunk-common', 'index'],
        },
        login: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'index.html',
            title: 'Вход',
            chunks: ['chunk-vendors', 'chunk-common', 'login'],
        },
        logout: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'index.html',
            title: 'Выход',
            chunks: ['chunk-vendors', 'chunk-common', 'logout'],
        },
        users: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'users.html',
            title: 'Клиенты',
            chunks: ['chunk-vendors', 'chunk-common', 'users'],
        },
        about: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'about.html',
            title: 'О нас',
            chunks: ['chunk-vendors', 'chunk-common', 'about'],
        },
        products: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'products.html',
            title: 'Продукты',
            chunks: ['chunk-vendors', 'chunk-common', 'products'],
        },
        payments: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'payments.html',
            title: 'Платежи',
            chunks: ['chunk-vendors', 'chunk-common', 'payments'],
        },
        orders: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'orders.html',
            title: 'Заказы',
            chunks: ['chunk-vendors', 'chunk-common', 'orders'],
        },
        offers: {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'offers.html',
            title: 'Акции',
            chunks: ['chunk-vendors', 'chunk-common', 'offers'],
        },
    },
}
