server:
  port: 9002
  servlet:
    context-path: /chi100easy/api

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chi100easy
      username: mongo
      password: secret
